export const types = {
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_MODAL_DATA: 'GET_MODAL_DATA',
    REMOVE_MODAL_DATA: 'REMOVE_MODAL_DATA',
    IS_MODAL_OPEN: 'IS_MODAL_OPEN',
    ADD_FAVOURITE_PRODUCT: 'ADD_FAVOURITE_PRODUCT',
    DELETE_FAVOURITE_PRODUCT: 'DELETE_FAVOURITE_PRODUCT',
    ADD_CART_ITEMS: 'ADD_CART_ITEMS',
    DELETE_CART_ITEMS: 'DELETE_CART_ITEMS',
    CLEAR_CART: 'CLEAR_CART',
};
